### ISSUE TITLE
applications crashes when reading shapefile

### ISSUE THREAD

**Issue by james2432** [osmottawa/etl2osm#28]
james@debian:~/Desktop/test$ etl2osm "/home/james/Desktop/test/Tree-Inventory.shp" --config "/home/james/Desktop/test/lol.json" --outfile "/home/james/Desktop/test/out.osm"
ERROR:root:No Models Found - Verify <FILE PATH: > or <FILE TYPE: .yml .json>.
Traceback (most recent call last):
  File "/usr/local/bin/etl2osm", line 9, in <module>
    load_entry_point('etl2osm==0.0.3', 'console_scripts', 'etl2osm')()
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 700, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/etl2osm-0.0.3-py2.7.egg/etl2osm/cli.py", line 18, in cli
    etl2osm.process(infile, outfile, config=config, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/etl2osm-0.0.3-py2.7.egg/etl2osm/api.py", line 16, in process
    data.transform(config, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/etl2osm-0.0.3-py2.7.egg/etl2osm/extract.py", line 193, in transform
    self.properties = config_to_properties(config)
  File "/usr/local/lib/python2.7/dist-packages/etl2osm-0.0.3-py2.7.egg/etl2osm/transform.py", line 43, in config_to_properties
    for key, value in config.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by DenisCarriere** [comment]
@james2432 Fixed some issues, it might not be related to this error, but might work now... I'm only supporting YAML at the moment.

Try parsing the address file using `etl2osm` to see if it works for you, I was able to parse it using this config:

http://opendata.peelregion.ca/data-categories/regional-geography/address-points.aspx

```yaml
'addr:street':
    - model: suffix
      field: STREETTYPE
    - title: True
      field: STREETNAME
    - model: direction
      field: STREETDIRE
'addr:housenumber':
    int: True
    field: STREETNUM
'addr:unit':
    UNIT_IDENT
ref:
    ROPADRID
'source:ref':
    text: 'Region of Peel'
source:
    text: 'Region of Peel'
```

**Comment by DenisCarriere** [comment]
I fixed some issues, it might be related to this error, but it wasn't working for me too.

My configs are using YAML files instead of JSON, I might drop JSON support.

@james2432 Try to use this config on the 
```yaml
'addr:street':
    - model: suffix
      field: STREETTYPE
    - title: True
      field: STREETNAME
    - model: direction
      field: STREETDIRE
'addr:housenumber':
    int: True
    field: STREETNUM
'addr:unit':
    UNIT_IDENT
ref:
    ROPADRID
'source:ref':
    text: 'Region of Peel'
source:
    text: 'Region of Peel'
```
